diff -Naur kernel-module-imx-gpu-viv-6.0.3.1_org/kernel-module-imx-gpu-viv-src/Kbuild kernel-module-imx-gpu-viv-6.0.3.1/kernel-module-imx-gpu-viv-src/Kbuild
--- kernel-module-imx-gpu-viv-6.0.3.1_org/kernel-module-imx-gpu-viv-src/Kbuild	2016-04-06 14:07:37.452092106 -0500
+++ kernel-module-imx-gpu-viv-6.0.3.1/kernel-module-imx-gpu-viv-src/Kbuild	2016-04-06 14:08:02.780217701 -0500
@@ -85,8 +85,6 @@
 CUSTOMER_ALLOCATOR_OBJS    ?=
 ALLOCATOR_ARRAY_H_LOCATION ?= $(OS_KERNEL_DIR)/allocator/default/
 
-EXTRA_CFLAGS += -Werror
-
 OBJS := $(OS_KERNEL_DIR)/gc_hal_kernel_device.o \
         $(OS_KERNEL_DIR)/gc_hal_kernel_linux.o \
         $(OS_KERNEL_DIR)/gc_hal_kernel_math.o \
