diff -Naur xserver-xorg-video-imx-viv-3.10.53-1.1.0_org/Makefile xserver-xorg-video-imx-viv-3.10.53-1.1.0/Makefile
--- xserver-xorg-video-imx-viv-3.10.53-1.1.0_org/Makefile	2014-11-07 13:19:57.911954378 -0600
+++ xserver-xorg-video-imx-viv-3.10.53-1.1.0/Makefile	2014-11-07 13:20:41.000000000 -0600
@@ -27,6 +27,8 @@
 	chmod 700 $(prefix)/bin/autohdmi
 	mkdir -p $(prefix)/lib/
 	cp $(TOPDIR)/FslExt/src/libfsl_x11_ext.so $(prefix)/lib/
+	mkdir -p $(prefix)/lib/xorg/modules/drivers/
+	cp $(TOPDIR)/EXA/src/vivante_drv.so $(prefix)/lib/xorg/modules/drivers/
 
 clean:
 	$(MAKE) -C $(TOPDIR)/util/autohdmi -f makefile.linux $@
