SRCREV_opencv = "5423d53ae0d116ee5bbe52f8b5503f0cd8586998"
PACKAGECONFIG_OPENCL:mx8mnul = ""
PACKAGECONFIG_OPENCL:mx8mpul = ""

# Use the protobuf from opencv source
PACKAGECONFIG[dnn] = "-DBUILD_opencv_dnn=ON -DPROTOBUF_UPDATE_FILES=ON -DBUILD_PROTOBUF=OFF,-DBUILD_opencv_dnn=OFF"
