# i.MX DISTRO with Wayland

require conf/distro/include/fsl-imx-base.inc

DISTRO = "fsl-imx-wayland"
DISTRO_NAME = "NXP i.MX Distro with Wayland"

# Remove conflicting backends
DISTRO_FEATURES:remove = "directfb x11 "
DISTRO_FEATURES:append = " wayland pam systemd"
