# i.MX DISTRO with Wayland

require conf/distro/include/fsl-imx-base.inc
require conf/distro/include/fsl-imx-extended.inc

DISTRO = "fsl-imx-wayland"
DISTRO_NAME = "NXP i.MX Distro with Wayland"

DISTRO_FEATURES:remove = "x11"
