# i.MX Minimal DISTRO with Framebuffer

require conf/distro/include/fsl-imx-base.inc

DISTRO = "fsl-imx-fb-minimal"
DISTRO_NAME = "NXP i.MX Minimal Distro with Framebuffer"

# Remove conflicting backends.
DISTRO_FEATURES:remove = "x11 wayland directfb "
