# i.MX DISTRO with Wayland and XWayland

require conf/distro/include/fsl-imx-base.inc
require conf/distro/include/fsl-imx-extended.inc

DISTRO = "fsl-imx-xwayland"
DISTRO_NAME = "NXP i.MX Distro with Wayland and XWayland"

PACKAGECONFIG:append:pn-weston      = " rdp"
PACKAGECONFIG:append:pn-weston-init = " rdp"
