# i.MX Minimal DISTRO with Wayland and XWayland

require conf/distro/include/fsl-imx-base.inc

DISTRO = "fsl-imx-xwayland-minimal"
DISTRO_NAME = "NXP i.MX Minimal Distro with Wayland and XWayland"

# Remove conflicting backends
DISTRO_FEATURES:remove = "directfb "
DISTRO_FEATURES:append = " x11 wayland pam"

PACKAGECONFIG:append:pn-weston      = " rdp"
PACKAGECONFIG:append:pn-weston-init = " rdp"
