# i.MX DISTRO with Framebuffer

require conf/distro/include/fsl-imx-base.inc
require conf/distro/include/fsl-imx-extended.inc

DISTRO = "fsl-imx-fb"
DISTRO_NAME = "NXP i.MX Distro with Framebuffer"

DISTRO_FEATURES:remove = "x11 wayland"
DISTRO_FEATURES:remove:mx6-nxp-bsp = "vulkan"
DISTRO_FEATURES:remove:mx7-nxp-bsp = "vulkan"
