# i.MX Minimal DISTRO with Wayland

require conf/distro/include/fsl-imx-base.inc

DISTRO = "fsl-imx-wayland-minimal"
DISTRO_NAME = "NXP i.MX Minimal Distro with Wayland"

DISTRO_FEATURES:remove = "x11"
