#@TYPE: Machine
#@NAME: i.MX 8QuadMax consolidated rootfs machine
#@SOC: i.MX8QM
#@DESCRIPTION: A consolidated machine configuration for i.MX 8QuadMax Multisensory Enablement Kit board, rev B0, see Important Note below
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

#        ** Important Note **
# This machine generates an image contain the bootloader of MEK, Kernel, and rootfs, plus the DTBs of
# both revd and lpddr4 validations. The resulting image can be used for MEK directly.
MACHINEOVERRIDES =. "imx8qm-mek:"
require conf/machine/imx8qm-mek.conf

KERNEL_DEVICETREE += " \
    freescale/imx8qm-lpddr4-val-ca53.dtb \
    freescale/imx8qm-lpddr4-val-ca72.dtb \
    freescale/imx8qm-lpddr4-val-dp.dtb \
    freescale/imx8qm-lpddr4-val.dtb \
    freescale/imx8qm-lpddr4-val-lpspi.dtb \
    freescale/imx8qm-lpddr4-val-lpspi-slave.dtb \
    freescale/imx8qm-lpddr4-val-mqs.dtb \
    freescale/imx8qm-lpddr4-val-spdif.dtb \
"
