# DEPRECATED: Machine is renamed, please use imx8mnul-ddr3l-evk
MACHINEOVERRIDES =. "imx8mnul-ddr3l-evk:"
require conf/machine/imx8mnul-ddr3l-evk.conf

IMAGE_BOOT_FILES:append = " \
    mcore-demos/imx8mnddr3l_m7_DDR_hello_world.bin \
    mcore-demos/imx8mnddr3l_m7_DDR_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx8mnddr3l_m7_DDR_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx8mnddr3l_m7_DDR_sai_low_power_audio.bin \
"
