#@TYPE: Machine
#@NAME: NXP i.MX 95 A1 19x19 Evaluation Kit with LPDDR5
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 Rev A1 19x19 EVK with LPDDR5
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

require imx95-19x19-lpddr5-evk.conf
IMX_SOC_REV:${MACHINE} = "A0"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    freescale/imx95a1-19x19-evk.dtb \
    freescale/imx95a1-19x19-evk-cs42888.dtb \
    freescale/imx95a1-19x19-evk-it6263-lvds0.dtb \
    freescale/imx95a1-19x19-evk-netc-rpmsg.dtb \
    freescale/imx95a1-19x19-evk-tja1103-rmii.dtb \
"
