#@TYPE: Machine
#@NAME: NXP i.MX 95 A1 15x15 Evaluation Kit with LPDDR4x
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 Rev A1 15x15 EVK with LPDDR4x
##@MAINTAINER: Jun Zhu <junzhu@nxp.com>

require imx95-15x15-lpddr4x-evk.conf
IMX_SOC_REV:${MACHINE} = "A0"
OEI_DDRCONFIG = "XIMX95LPD4XCPU15_4000mbps_train_timing_a1"
