#@TYPE: Machine
#@NAME: NXP i.MX 95 A1 19x19 Evaluation Kit with LPDDR5
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 Rev A1 19x19 EVK with LPDDR5
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

require imx95-19x19-lpddr5-evk.conf
IMX_SOC_REV:${MACHINE} = "A0"
OEI_DDRCONFIG = "XIMX95LPD5EVK19_6400mbps_train_timing_a1"
